/**
 * Génère zh.json complet en fusionnant en.json + traductions chinoises intégrales
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const localesDir = path.join(__dirname, '../i18n/locales')

function deepMerge(target, source) {
  for (const k of Object.keys(source)) {
    if (source[k] && typeof source[k] === 'object' && !Array.isArray(source[k])) {
      if (!target[k] || typeof target[k] !== 'object') target[k] = {}
      deepMerge(target[k], source[k])
    } else {
      target[k] = source[k]
    }
  }
  return target
}

/** Traductions chinoises (écrase les valeurs anglaises de en.json) */
const zh = {
  nav: {
    home: '首页',
    personalShopping: '代购服务',
    importExport: '进出口',
    tracking: '包裹跟踪',
    calculator: '运费计算器',
    visa: '中国签证',
    guide: '导游陪同',
    resources: '资源中心',
    pricing: '价格',
    blog: '博客',
    faq: '常见问题',
    admin: '管理',
    trackPackage: '跟踪包裹',
    language: '语言',
    howItWorks: '如何运作',
    ourServices: '我们的服务',
    pages: '页面',
    aboutUs: '关于我们',
    contact: '联系我们',
    privacy: '隐私政策',
    terms: '条款与条件',
    chinese: '中文',
  },
  home: {
    heroTitle: '您与中国进出口的合作伙伴',
    heroSubtitle: '代购、货运、签证和专业陪同服务',
    heroBadge: '#1 中非进出口',
    ctaStart: '立即开始',
    ctaLearnMore: '了解更多',
    servicesTitle: '我们的服务',
    servicesSubtitle: '满足您进出口需求的完整解决方案',
    servicesBadge: '我们提供的服务',
    whyUsTitle: '为什么选择我们？',
    whyUsSubtitle: '中非贸易领域公认的专业经验',
    howItWorks: '如何运作？',
    howItWorksBadge: '简单快捷',
    howItWorksSubtitle: '简单高效的5步流程',
    categoriesTitle: '产品类别',
    categoriesSubtitle: '找到您需要的一切',
    latestArticles: '最新文章',
    ctaTitle: '准备开始了吗？',
    ctaSubtitle: '提交您的第一个请求或联系我们了解更多',
    statsClients: '满意客户',
    statsPackages: '已送达包裹',
    statsCountries: '服务国家',
    statsYears: '年经验',
    steps: {
      step1: '发送图片',
      step1Desc: '所需产品照片',
      step2: '沟通洽谈',
      step2Desc: '通过 WhatsApp 交流',
      step3: '获取报价',
      step3Desc: '收到您的报价',
      step4: '付款确认',
      step4Desc: '确认并付款',
      step5: '配送收货',
      step5Desc: '收到您的包裹',
    },
  },
  services: {
    personalShopping: {
      title: '代购服务',
      description: '我们在中国为您采购。发送产品参考信息，其余交给我们处理。',
      features: ['产品搜寻', '价格谈判', '质量检验', '安全运输'],
    },
    shipping: {
      title: '货运服务',
      description: '将您的货物从中国通过空运或海运运送至非洲。',
      features: ['空运快递', '空运标准', '海运', '实时跟踪'],
    },
    visa: {
      title: '中国签证',
      description: '协助您完整办理中国签证。',
      features: ['旅游签证', '商务签证', '工作签证', '材料辅导'],
    },
    guide: {
      title: '导游与陪同',
      description: '专业导游在您中国行程中全程陪同。',
      features: ['口译翻译', '供应商拜访', '商务谈判', '本地物流'],
    },
  },
  personalShopping: {
    title: '代购服务',
    subtitle: '无需亲赴中国即可找到任何产品。我们的当地代理为您搜寻、议价并发货。',
    badge: '尊享服务',
    newRequest: '新建请求',
    myRequests: '我的请求',
    myCart: '购物车',
    addToCart: '加入购物车',
    categories: '分类',
    allCategories: '全部分类',
    categoriesTitle: '产品分类',
    categoriesSubtitle: '我们能找到各类产品',
    howItWorks: '简单快捷',
    processTitle: '如何运作？',
    processSubtitle: '简单的5步流程',
    pricingTitle: '我们的价格',
    pricingSubtitle: '费用完全透明',
    whyUs: '为什么选择我们？',
    ctaTitle: '准备好找产品了吗？',
    ctaSubtitle: '立即提交请求，48小时内收到报价',
    pricing: {
      search: '搜寻费用',
      searchDesc: '在中国为您搜寻产品',
      free: '免费',
      commission: '采购佣金',
      commissionDesc: '按产品价格的百分比计算',
      inspection: '质量检验',
      inspectionDesc: '发货前质量核查',
      packaging: '安全包装',
      packagingDesc: '保护您的产品',
      shipping: '运输',
      shippingDesc: '按重量和目的地计算',
      calculate: '计算',
    },
    form: {
      title: '创建请求',
      productName: '产品名称',
      category: '分类',
      quantity: '数量',
      budget: '预估预算',
      description: '描述',
      images: '产品图片',
      uploadImages: '上传图片',
      dragDrop: '将图片拖放到此处',
      or: '或',
      browse: '浏览',
      submit: '提交请求',
      preview: '预览',
    },
    status: {
      pending: '待处理',
      searching: '搜寻中',
      negotiating: '议价中',
      confirmed: '已确认',
      preparing: '准备中',
      shipped: '已发货',
      delivered: '已送达',
      cancelled: '已取消',
    },
  },
  importExport: {
    title: '进出口',
    subtitle: '将货物从中国运往非洲。空运、海运、包裹集运、清关服务。',
    shippingModes: '运输方式',
    shippingModesSubtitle: '选择适合您需求的运输方式',
    airExpress: '空运快递',
    airExpressDesc: '紧急包裹快速送达',
    airExpressTransit: '3-5天运输',
    airExpressTracking: '实时跟踪',
    airExpressIdeal: '适合小件包裹',
    airStandard: '空运标准',
    airStandardDesc: '性价比最优',
    airStandardTransit: '15-18天运输',
    airStandardTracking: '定期跟踪',
    airStandardIdeal: '适合各类包裹',
    seaFreight: '海运',
    seaFreightDesc: '大批量更经济',
    seaFreightTransit: '30-45天运输',
    seaFreightPrice: '极具竞争力的价格',
    seaFreightIdeal: '适合大批量',
    destinations: '目的地',
    destinationsSubtitle: '我们覆盖整个非洲',
    consolidation: '集运',
    consolidationDesc: '合并不同供应商的采购',
    securePacking: '安全包装',
    securePackingDesc: '为您的货物提供最佳保护',
    customsClearance: '清关',
    customsClearanceDesc: '协助完成全部手续',
    delivery: '配送',
    deliveryDesc: '提供门到门配送',
    ctaTitle: '计算您的运费',
    ctaSubtitle: '即时获取估算',
    useCalculator: '使用计算器',
  },
  calculator: {
    title: '运费计算器',
    subtitle: '估算您的货物运输费用',
    destinationCountry: '目的地国家 *',
    selectCountry: '选择国家',
    shippingMode: '运输方式 *',
    totalWeight: '总重量 (kg) *',
    weightHint: '实际重量或体积重量（取较大值）',
    calculate: '计算',
    costEstimate: '费用估算',
    destination: '目的地',
    mode: '方式',
    weight: '重量',
    shippingCost: '运费',
    insurance: '保险 (1%)',
    handling: '操作费',
    estimatedDelay: '预计时效',
    ratePerKg: '每公斤费率',
    rateDetail: '明细：{rate} / kg × {weight} kg（服务器端四舍五入）',
    calculating: '计算中...',
    calcFailed: '无法计算费率，请检查目的地和运输方式。',
    noDestinations: '尚未配置目的地，请联系 NADOM。',
    rateNotConfigured: '费率未设置 — 请在后台（每公斤费率）中配置。',
    currencyScopeNote: '金额以该目的地配置的货币显示（ISO 4217）。',
    totalEstimate: '预估总计',
    customsNote: '此估算不含关税，关税取决于货物性质。请联系我们获取精确报价。',
    getPreciseQuote: '获取精确报价',
    orderViaShopping: '通过代购下单',
    whatsappQuoteGreeting: '您好 NADOM，',
    whatsappQuoteIntro: '我在运费计算器上估算后，希望获得精确报价：',
    whatsappQuoteBullet: '-',
    whatsappQuoteClosing: '期待您的回复，谢谢。',
  },
  tracking: {
    title: '包裹跟踪',
    subtitle: '实时跟踪您的包裹',
    placeholder: '输入跟踪号',
    search: '搜索',
    packageNotFound: '未找到包裹',
    noPackageMatch: '没有匹配的包裹编号',
    checkNumber: '请检查跟踪号或联系客服。',
    realTimeTracking: '实时跟踪',
    trackEveryStep: '每一步都可跟踪您的包裹',
    notifications: '通知',
    alertsWhatsApp: '通过 WhatsApp 接收提醒',
    support247: '24/7 客服',
    teamHelp: '我们的团队随时为您服务',
    currentLocation: '当前位置',
    history: '历史记录',
    contactSupport: '联系客服',
    newSearch: '新搜索',
    shippingDate: '发货日期',
    estimatedDelivery: '预计送达',
    status: {
      pending: '待处理',
      picked_up: '已揽收',
      in_transit: '运输中',
      in_customs: '清关中',
      out_for_delivery: '派送中',
      delivered: '已送达',
    },
    placeholderLong: '请输入跟踪号（例如：TRK-2024-001234）',
    projectDetails: '项目详情',
    projectTitle: '标题',
    projectCategory: '类别',
    projectStatus: '项目状态',
    projectImages: '项目图片',
    timeline: '步骤历史',
    psOnlyHint: '您的请求已登记。创建运输后，包裹跟踪信息也会显示在此处。',
    details: {
      trackingNumber: '跟踪号',
      destination: '目的地',
      weight: '重量',
      estimatedDelivery: '预计送达',
      currentLocation: '当前位置',
      timeline: '时间线',
    },
  },
  pricing: {
    title: '我们的价格',
    subtitle: '进出口服务价格透明公开',
    shippingRates: '运费',
    servicesFees: '服务费',
    faq: '常见问题',
    getQuote: '获取报价',
    perKg: '每公斤',
    commission: '佣金',
    from: '起价',
    chooseFormula: '选择您的方案',
    adaptedRates: '根据您的需求定制价格',
    personalShopping: '代购服务',
    searchPurchase: '产品搜寻与采购',
    productSearch: '产品搜寻',
    priceNegotiation: '价格谈判',
    qualityControl: '质量检验',
    photosBeforeShipping: '发货前拍照',
    whatsappTracking: 'WhatsApp 跟踪',
    shipping: '运输',
    goodsTransport: '货物运输',
    popular: '热门',
    airExpress: '空运快递 (3-5天)',
    airStandard: '空运标准 (15-18天)',
    seaFreight: '海运 (30-45天)',
    securePacking: '安全包装',
    realTimeTracking: '实时跟踪',
    insuranceIncluded: '含保险',
    calculateRate: '计算我的运费',
    additionalServices: '附加服务',
    visaGuides: '签证、导游等',
    variableAccording: '根据',
    service: '服务类型',
    chinaVisaAssistance: '中国签证协助',
    frenchGuides: '法语导游',
    factoryVisits: '工厂参观',
    interpretation: '口译',
    marketAccompaniment: '市场陪同',
    shippingRatesTable: '运费价格表',
    ratesPerKg: '按目的地和方式的每公斤费率',
    destination: '目的地',
    airExpressTitle: '空运快递',
    airExpressDays: '(3-5天)',
    airStandardTitle: '空运标准',
    airStandardDays: '(15-18天)',
    seaTitle: '海运',
    seaDays: '(30-45天)',
    noDestinations: '尚未配置目的地，请稍后再来或联系我们获取定制报价。',
    indicativeRates: '以上费率为参考价，可能因货量和货物类型而有所变化。',
    useCalculator: '使用我们的计算器',
    preciseEstimate: '获取精确估算。',
    faqCommission: '佣金如何计算？',
    faqCommissionAnswer: '5%佣金按产品采购价计算，涵盖搜寻、议价、质量检验及与供应商协调。',
    faqHiddenFees: '有隐藏费用吗？',
    faqHiddenFeesAnswer: '没有，所有费率透明公开。额外费用可能仅为关税，取决于货物性质，由您所在国家规定。',
    faqPayment: '接受哪些付款方式？',
    faqPaymentAnswer: '我们接受银行转账、Orange Money、Wave 和 Western Union。通常分两次付款：下单时付定金，发货前付尾款。',
    needQuote: '需要定制报价？',
    needQuoteDesc: '大批量订单或特殊需求，请联系我们获取项目专属报价。',
    contactForm: '联系表单',
  },
  visa: {
    title: '中国签证',
    subtitle: '协助办理中国签证：商务、旅游、留学或工作签证。',
    badge: '尊享服务',
    types: {
      tourism: '旅游签证',
      business: '商务签证',
      work: '工作签证',
      study: '留学签证',
    },
    duration: '停留期限',
    validity: '有效期',
    processingTime: '办理时间',
    requiredDocs: '所需材料',
    otherDocs: '其他文件',
    downloadForm: '下载表格',
    requestQuote: '索取报价',
    applyNow: '立即申请',
    processSection: '简单快捷',
    processTitle: '办理流程',
    processSubtitle: '我们简化您的手续',
    faqTitle: '常见问题',
    noVisa: '暂无可用签证',
    noVisaInfo: '联系我们了解更多信息。',
    ctaTitle: '需要中国签证？',
    ctaSubtitle: '联系我们免费评估您的材料',
  },
  guide: {
    title: '导游与陪同',
    subtitle: '法语导游陪同您在中国的商务行程：市场考察、工厂参观和商务谈判。',
    badge: '本地专业',
    docTitle: '指南与文档',
    docSubtitle: '进出口实务资源',
    interpretersTitle: '口译与陪同',
    interpretersSubtitle: '我们在中国的专业导游',
    downloadPdf: '下载',
    viewDoc: '查看',
    requestDoc: '索取文档',
    filterCity: '城市',
    filterSpec: '专长',
    filterLang: '语言',
    allCities: '全部城市',
    allSpecs: '全部专长',
    allLangs: '全部语言',
    ourServices: '我们的专长',
    servicesTitle: '陪同服务',
    ctaTitle: '规划您的商务行程',
    ctaSubtitle: '联系我们安排您在华的行程',
    services: '提供的服务',
    book: '预订',
    learnMore: '了解更多',
    bookWhatsapp: '通过 WhatsApp 联系',
    bookingTitle: '预订陪同人员',
    bookingDocTheme: '指南与文档主题（可选）',
    bookingDocThemeHint: '请注明主题（进口、海关、货运等），以便我们准备您的任务。',
    bookingDocThemeNone: '无特定主题',
    bookingStart: '开始日期',
    bookingEnd: '结束日期',
    bookingServiceType: '服务类型',
    bookingDaily: '按天',
    bookingHourly: '按小时',
    bookingHours: '小时数',
    bookingPeopleCount: '需陪同人数',
    bookingPeopleCountHint: '需要引导的人数（团队/代表团），不含导游本人。',
    bookingNotes: '备注或特殊需求',
    bookingSubmit: '提交请求',
    bookingSuccess: '请求已提交，我们将尽快与您联系。',
    bookingNeedLogin: '请登录后预订陪同人员。',
    bookingInvalidDates: '结束日期必须等于或晚于开始日期。',
    noGuide: '暂无可用导游',
    contactInfo: '联系我们了解更多信息。',
    yearsExp: '年经验',
    from: '起价',
    perDay: '天',
    available: '可用',
    unavailable: '不可用',
    noGuideFound: '未找到导游',
    adjustFilters: '请调整搜索筛选条件',
    all: '全部',
  },
  blog: {
    title: '博客与资讯',
    subtitle: '中非进出口技巧与资讯',
    readMore: '阅读更多',
    categories: '分类',
    recentPosts: '最新文章',
    tags: '标签',
    share: '分享',
    shareArticle: '分享本文',
    author: '作者',
    publishedOn: '发布于',
    readTime: '分钟阅读',
    noArticles: '暂无文章',
    notFound: '文章未找到',
    notFoundDesc: '该文章不存在或已被删除。',
    backToBlog: '返回博客',
    ctaTitle: '准备开始您的进口项目？',
    ctaDesc: '联系我们讨论您的项目并获取定制报价。',
    introduction: '简介',
    introText1: '与中国进出口是非洲创业者的重大机遇。数以百万计的产品以有竞争力的价格供应，中国仍是全球最多样化商品的主要供应国。',
    introText2: '本文将探讨进出口操作的成功步骤、应避免的陷阱以及优化成本的最佳实践。',
    advantagesTitle: '从中国进口的优势',
    advantage1: '有竞争力的价格：',
    advantage1Desc: '中国的生产成本可带来可观的利润空间。',
    advantage2: '选择广泛：',
    advantage2Desc: '各类产品数以百万计可供选择。',
    advantage3: '生产能力：',
    advantage3Desc: '中国工厂可处理各种规模的订单。',
    advantage4: '创新领先：',
    advantage4Desc: '中国在许多技术领域处于前沿。',
    quote: '进出口成功的关键，是有一位了解当地情况的可靠合作伙伴。',
    quoteAuthor: 'NADOM 专家',
    stepsTitle: '进口关键步骤',
    stepIdentify: '确定产品：',
    stepIdentifyDesc: '精确定义您要进口的产品。',
    stepSupplier: '寻找供应商：',
    stepSupplierDesc: '使用我们的代购服务找到最佳供应商。',
    stepNegotiate: '谈判条款：',
    stepNegotiateDesc: '价格、最小起订量、生产周期。',
    stepQuality: '质量检验：',
    stepQualityDesc: '发货前检验产品。',
    stepShipping: '运输：',
    stepShippingDesc: '选择适合您需求的运输方式。',
    tip: '建议：',
    tipText: '先以小批量测试市场和质量，再下大订单。',
    conclusion: '结论',
    conclusionText1: '遵循最佳实践，与中国进出口可以非常盈利。建议寻求专业支持以保障您的业务安全。',
    conclusionText2: 'NADOM 在项目的每一步为您提供支持，从产品搜寻到送货上门。',
  },
  auth: {
    login: '登录',
    logout: '退出',
    adminLogin: '管理员登录',
    clientAccess: '客户访问',
    email: '电子邮件',
    password: '密码',
    trackingCode: '跟踪码',
    enterCode: '输入您的跟踪码',
    accessMyRequests: '访问我的请求',
    forgotPassword: '忘记密码？',
    noAccount: '没有账户？',
    hasCode: '有跟踪码？',
    adminOnly: '仅限管理员',
    welcome: '欢迎来到 NADOM',
    welcomeSubtitle: '您值得信赖的中非进出口合作伙伴。',
    secureShipping: '安全运输',
    trackOrder: '跟踪您的订单',
    trackOrderHint: '输入跟踪码以访问您的请求和包裹',
    trackingPlaceholder: '例如：TRK-2024-001234 或 REQ-001234',
    trackingHint: '包裹跟踪号或请求编号',
    noCode: '没有代码？',
    passwordPlaceholder: '您的密码',
    backHome: '返回首页',
    staffOnly: '仅限授权人员',
    loginSuccess: '登录成功！',
    loginError: '登录时出错',
    checkoutError: '结账时出错。',
  },
  common: {
    loading: '加载中...',
    error: '发生错误',
    success: '操作成功',
    cancel: '取消',
    save: '保存',
    edit: '编辑',
    delete: '删除',
    confirm: '确认',
    back: '返回',
    next: '下一步',
    previous: '上一步',
    search: '搜索',
    filter: '筛选',
    all: '全部',
    viewAll: '查看全部',
    viewDetails: '查看详情',
    contactUs: '联系我们',
    learnMore: '了解更多',
    getStarted: '开始',
    currency: 'FCFA',
  },
  footer: {
    about: '关于',
    aboutText: 'NADOM 是您值得信赖的中国进出口合作伙伴。',
    quickLinks: '快速链接',
    services: '服务',
    contact: '联系',
    followUs: '关注我们',
    newsletter: '订阅通讯',
    newsletterText: '接收我们的最新消息',
    subscribe: '订阅',
    rights: '版权所有',
  },
  faq: {
    title: '常见问题',
    noQuestions: '暂无问题。',
  },
  cart: {
    addedToCart: '产品已加入购物车',
    requestAdded: '请求已加入购物车',
    orderTitle: '订购 {n} 件商品',
    orderSent: '请求已发送！我们的团队将在24小时内与您联系。',
    whatsappIntro: '您好 NADOM，我想订购：\n\n',
  },
  contact: {
    fieldLengths: '请遵守每个字段所示的最大长度。',
  },
  about: {
    watchPromo: '了解我们的服务',
  },
  admin: {
    title: '管理后台',
    verifyingAccess: '正在验证访问权限...',
    nav: {
      dashboard: '仪表板',
      fretLogistics: '货运与物流',
      catalogShop: '商店目录',
      travelServices: '旅行与服务',
      siteContent: '网站内容',
      supportSystem: '支持与系统',
      teamAccess: '团队与权限',
      requests: '请求',
      shipments: '运输',
      freightDestinations: '货运目的地',
      ratesPerKg: '每公斤费率',
      categories: '分类',
      products: '产品',
      personalShopping: '代购服务',
      guides: '导游',
      accompaniment: '陪同服务',
      guideBookings: '导游预订',
      visas: '签证',
      gridsRates: '价格表',
      blog: '博客',
      faq: '常见问题',
      homeBlock: '首页区块',
      aboutContact: '关于我们 & 联系',
      footer: '页脚',
      contactLeads: '联系请求',
      support: '客服',
      reports: '报告',
      settings: '设置',
      users: '用户',
      countries: '国家',
      rolesProfiles: '角色与权限',
      activityLog: '活动日志',
      backToSite: '返回网站',
      notifications: '通知',
      markAllRead: '全部标为已读',
      noUnreadNotifications: '没有未读通知',
      viewAllNotifications: '查看全部',
      myProfile: '我的资料',
      logout: '退出登录',
    },
    pages: {
      dashboard: '仪表板',
      requests: '请求管理',
      shipments: '运输管理',
      destinations: '货运目的地（计算器）',
      shippingModes: '每公斤费率（计算器）',
      users: '用户管理',
      roles: '角色管理',
      guides: '导游管理',
      guideServices: '陪同服务（导游）',
      guideBookings: '导游预订',
      visas: '签证管理',
      pricing: '价格管理',
      blog: '博客管理',
      faq: 'FAQ 管理',
      homeServices: '服务（首页）',
      sitePages: '关于 & 联系页面',
      footer: '页脚（网站）',
      support: '客户支持',
      activityLogs: '活动日志',
      countries: '国家（参考）',
      reports: '报告',
      notifications: '通知',
      settings: '设置',
      categories: '分类',
      products: '产品',
      personalShopping: '代购服务',
      contactLeads: '联系请求（网站）',
    },
    time: {
      justNow: '刚刚',
      minutesAgo: '{n} 分钟前',
      hoursAgo: '{n} 小时前',
      daysAgo: '{n} 天前',
    },
    dashboard: {
      title: '仪表板',
      subtitle: 'NADOM 活动摘要。',
      total: '总计',
      registeredRequests: '已登记请求',
      pending: '待处理',
      pendingRequests: '待处理请求',
      transit: '运输中',
      inTransitPackages: '运输中包裹',
      revenue: '收入',
      invoicedQuotes: '已开票报价',
      recentRequests: '最近请求',
      viewAll: '查看全部',
      product: '产品',
      status: '状态',
      budgetQuote: '预算 / 报价',
      quote: '报价',
      date: '日期',
      noRequests: '暂无请求',
      statusDistribution: '状态分布',
      noData: '暂无数据',
      noTransitPackages: '无运输中包裹',
      quickActions: '快捷操作',
    },
    common: {
      new: '新建',
      newFeminine: '新建',
      edit: '编辑',
      delete: '删除',
      save: '保存',
      cancel: '取消',
      close: '关闭',
      search: '搜索',
      reset: '重置',
      filter: '筛选',
      apply: '应用',
      actions: '操作',
      active: '启用',
      inactive: '停用',
      all: '全部',
      allFeminine: '全部',
      loading: '加载中...',
      noResults: '无结果',
      yes: '是',
      no: '否',
      french: '法语',
      english: '英语',
      chinese: '中文',
      select: '选择',
      view: '查看',
      detail: '详情',
      exportPdf: '导出 PDF',
      exportExcel: '导出 Excel',
      retry: '重试',
      refresh: '刷新',
      anonymous: '匿名',
      items: '项',
      stable: '稳定',
      vsLastMonth: '较上月',
    },
    confirm: {
      deleteRequest: '确定删除此请求？',
      deleteTicket: '确定删除此工单？',
      deleteCategory: '确定删除此分类？',
      deleteProduct: '确定删除此产品？',
      deleteArticle: '确定删除此文章？',
      deleteGuide: '确定删除此导游？',
      deleteBooking: '确定删除此预订？',
      deleteDestination: '确定删除目的地「{name}」？',
      deleteRate: '确定删除此费率？',
      deleteCountry: '确定删除国家「{name}」？',
      deleteSetting: '确定删除参数「{key}」？',
      deleteSocialLink: '确定删除此链接？',
      deleteContactBlock: '确定删除此区块？',
      deleteStep: '确定要删除此步骤吗？',
      deleteContactLead: '确定删除此联系请求？',
    },
    requests: {
      title: '请求管理',
      newRequest: '新建请求',
      searchPlaceholder: '搜索...',
      allStatuses: '全部状态',
      allCategories: '全部分类',
      loading: '正在加载请求...',
      id: 'ID',
      client: '客户',
      budget: '预算',
      quote: '报价',
      shipment: '运输',
      noRequests: '未找到请求',
      linkShipment: '关联运输',
      selectShipment: '— 请选择 —',
      status: {
        pending: '待处理',
        searching: '搜寻中',
        negotiating: '议价中',
        confirmed: '已确认',
        preparing: '准备中',
        shipped: '已发货',
        delivered: '已送达',
        cancelled: '已取消',
      },
    },
    shipments: {
      title: '运输管理',
      newShipment: '新建运输',
      trackingPlaceholder: '跟踪号...',
      collected: '已揽收',
      inTransit: '运输中',
      inCustoms: '清关中',
      outForDelivery: '派送中',
      delivered: '已送达',
      loading: '正在加载运输...',
      trackingNumber: '跟踪号',
      request: '请求',
      destination: '目的地',
      mode: '方式',
      weight: '重量',
      noShipments: '未找到运输记录',
      airExpress: '空运快递',
      sea: '海运',
      airStandard: '空运标准',
      notFound: '未找到运输记录',
      backToList: '返回运输列表',
      logisticsInfo: '物流信息',
      dimensions: '尺寸 (长 × 宽 × 高)',
      declaredValue: '申报价值',
      shippingCost: '运费',
      currentLocation: '当前位置',
      timeline: '步骤历史',
      addStep: '添加步骤',
      noSteps: '暂无步骤记录。',
      estimatedDelivery: '预计送达',
      references: '参考信息',
      noPhone: '未提供电话号码',
      linkToRequest: '关联请求',
      packageLabel: '包裹标签',
      updateShipment: '更新运输',
      newStatus: '新状态',
      comment: '备注',
      editStep: '编辑步骤',
      saveChanges: '保存更改',
    },
    support: {
      title: '客户支持',
      newTicket: '新建工单',
      total: '总计',
      activeTickets: '进行中（开放 / 处理中 / 等待）',
      resolvedClosed: '已解决 & 已关闭',
      byStatus: '按状态',
      priority: '优先级',
      low: '低',
      normal: '普通',
      high: '高',
      urgent: '紧急',
      open: '开放',
      inProgress: '处理中',
      waiting: '等待中',
      resolved: '已解决',
      closed: '已关闭',
      createdFrom: '创建自',
      to: '至',
      subject: '主题',
      category: '分类',
      noTickets: '未找到工单',
    },
    reports: {
      title: '报告与统计',
      subtitle: '绩效与活动分析',
      deliveryCountry: '送达国家',
      allDestinations: '🌍 全部目的地',
      year: '年份',
      period: '期间',
      last12Months: '近12个月',
      last6Months: '近6个月',
      last3Months: '近3个月',
      thisMonth: '本月',
      turnover: '营业额',
      handledRequests: '已处理请求',
      newClients: '新客户',
      satisfactionRate: '满意度',
      monthlyEvolution: '月度趋势',
      topDestinations: '热门目的地',
    },
    users: {
      title: '用户管理',
      newUser: '新建用户',
      searchPlaceholder: '姓名、邮箱、电话...',
      allRoles: '全部角色',
      allStatuses: '全部状态',
      loading: '正在加载用户...',
      user: '用户',
      role: '角色',
      contact: '联系方式',
      location: '所在地',
      registered: '注册时间',
      noUsers: '未找到用户',
      firstName: '名',
      lastName: '姓',
      password: '密码',
      confirmPassword: '确认密码',
      profile: '角色',
      phone: '电话',
      gender: '性别',
      male: '男',
      female: '女',
      update: '更新',
      create: '创建用户',
      rolesTitle: '角色与权限',
      newRole: '新建角色',
      label: '标签',
      code: '代码',
      description: '描述',
      noRoles: '未找到角色',
      selectedProfile: '已选角色',
      selectRoleHint: '在表格中选择角色以管理权限。',
      modulesMenus: '模块 / 菜单',
      saveAccess: '保存权限',
      roleName: '角色名称',
      uniqueCode: '唯一代码',
      roleDescription: '职责简要描述...',
      updateRole: '更新',
      createRole: '创建角色',
      profileOf: '用户资料',
      editProfile: '编辑资料',
      deactivate: '停用',
      coordinates: '联系信息',
      notProvided: '未填写',
      registeredOn: '注册于',
      shoppingRequests: '代购请求',
      noUserRequests: '暂无请求',
      recipient: '收件人',
      track: '跟踪',
      noUserShipments: '暂无运输',
      city: '城市',
      selectCountry: '选择国家',
    },
    profile: {
      title: '我的资料',
      subtitle: '管理您的个人信息和密码。',
      administrator: '管理员',
      personalInfo: '个人信息',
      changePassword: '修改密码',
      newPassword: '新密码',
      saveChanges: '保存更改',
    },
    notifications: {
      title: '通知',
      unread: '未读',
      markAllRead: '全部标为已读',
      searchTitle: '按标题搜索...',
      read: '已读',
      unreadOnly: '未读',
      results: '条结果',
      none: '暂无通知',
      upToDate: '您已查看全部通知！',
      viewDetail: '查看详情',
    },
    products: {
      title: '产品管理',
      newProduct: '新建产品',
      searchPlaceholder: '搜索产品...',
      allCategories: '全部分类',
      category: '分类',
      price: '价格',
      description: '描述',
      noProducts: '未找到产品',
      nameFr: '产品名称 (FR)',
      nameEn: '产品名称 (EN)',
      describeFr: '描述产品...',
      describeEn: '请用英语描述产品...',
      selectCategory: '选择分类',
      currency: '货币',
      productImage: '产品图片',
      imageFormats: '支持格式：JPG、PNG、WebP，最大 2MB。',
      orUrl: '或 URL',
      demo: '演示',
      upload: '上传...',
    },
    blog: {
      title: '博客管理',
      newArticle: '新建文章',
      published: '已发布',
      drafts: '草稿',
      draft: '草稿',
      publishedStatus: '已发布',
      noArticles: '暂无文章',
      createFirst: '开始创建您的第一篇博客文章。',
      createArticle: '创建文章',
      titleFr: '标题 (FR)',
      excerptFr: '摘要 (FR)',
      contentFr: '内容 (FR)',
      titleEn: '标题 (EN)',
      excerptEn: '摘要 (EN)',
      contentEn: '内容 (EN)',
      slug: 'URL 别名 (slug)',
      news: '新闻',
      readTime: '阅读时间 (分钟)',
      author: '作者',
      image: '图片',
      upload: '上传…',
      tags: '标签（逗号分隔）',
    },
    faq: {
      title: 'FAQ 管理',
      newQuestion: '新建问题',
      question: '问题',
      noQuestions: '未找到问题',
      questionFr: '问题 (FR)',
      answerFr: '回答 (FR)',
      questionEn: '问题 (EN)',
      answerEn: '回答 (EN)',
      general: '常规',
    },
    categories: {
      title: '分类管理',
      newCategory: '新建分类',
      filterSlug: '按 slug 筛选（类型）',
      allTypes: '— 全部类型 —',
      linesPerPage: '行 / 页',
      order: '排序',
      archived: '已归档',
      none: '无',
      icon: '图标',
      viewIcons: '查看图标',
      selectSlug: '选择或创建 slug',
      addSlug: '添加此新 slug',
    },
    guides: {
      title: '导游管理',
      newGuide: '新建导游',
      searchPlaceholder: '搜索导游...',
      allTypes: '全部类型',
      interpreters: '口译陪同',
      documentation: '文档',
      available: '可用',
      unavailable: '不可用',
      type: '类型',
      languages: '语言',
      cities: '城市',
      experience: '经验',
      ratePerDay: '日费率',
      availability: '可用性',
      noGuides: '未配置导游',
      guideName: '导游姓名',
      interpreterVisits: '陪同（参观）',
      docFiles: '文档 / 文件',
      docUrl: '文档 URL',
      specializationsFr: '专长 (FR)',
      specializationsEn: '专长 (EN)',
      yearsExperience: '从业年数',
      availableForBooking: '可接受预订',
    },
    guideBookings: {
      title: '导游预订',
      confirmed: '已确认',
      completed: '已完成',
      cancelled: '已取消',
      resetFilters: '重置筛选',
      createdAt: '创建于',
      period: '期间',
      people: '人数',
      amount: '金额',
      noBookings: '暂无预订',
      docTheme: '文档主题',
      serviceType: '服务类型',
      peopleToAccompany: '需陪同人数',
      notes: '备注',
    },
    visas: {
      title: '签证管理',
      newVisa: '新建签证',
      duration: '期限',
      requiredDocs: '所需材料',
      viewPdf: '查看 PDF 表格',
      noVisas: '未配置签证',
      addVisa: '添加签证',
      visaNameFr: '签证名称 (FR)',
      visaNameEn: '签证名称 (EN)',
      validity: '有效期',
      processingTime: '办理时间',
      visaType: '签证类型',
      tourist: '旅游',
      business: '商务',
      transit: '过境',
      work: '工作',
      study: '留学',
      family: '家庭团聚',
      pdfForm: 'PDF 表格',
      visaActive: '签证启用',
    },
    pricing: {
      title: '服务与价格管理',
      newService: '新建服务',
      loadingServices: '正在加载服务...',
      noServices: '未配置服务',
      createService: '创建服务',
      serviceName: '服务名称',
      serviceActive: '服务启用',
    },
    countries: {
      title: '国家（参考）',
      newCountry: '新建国家',
      country: '国家',
      dialCode: '区号',
      displayOrder: '显示顺序',
      noCountries: '暂无国家。',
      countryLabel: '标签',
      countryCode: '国家代码',
      phoneDial: '电话区号',
      currencyRef: '货币（DVS 分类参考）',
      saving: '保存中…',
    },
    destinations: {
      title: '运输目的地',
      viewCalculator: '查看计算器',
      freightDestinations: '货运目的地',
      countriesPage: '国家 & 进出口页面',
      newDestination: '新建目的地',
      loadingCountries: '正在加载国家…',
      allCountries: '— 全部国家 —',
      noDestinations: '暂无目的地',
      textsSection: '文案 —「目的地」区块',
      titleFr: '标题 (FR)',
      titleEn: '标题 (EN)',
      subtitleFr: '副标题 (FR)',
      subtitleEn: '副标题 (EN)',
      saveTexts: '保存文案',
      city: '城市',
      continent: '大洲',
      flagEmoji: '国旗 (emoji)',
      currencyIso: '货币 (ISO 4217)',
    },
    shippingModes: {
      title: '每公斤费率',
      newRate: '新建费率',
      filterByCountry: '按国家筛选',
      airExpress: '空运快递',
      airStandard: '空运标准',
      boat: '海运',
      indicativeDelay: '预计时效',
      ratePerKg: '费率 / kg',
      chooseCountry: '选择国家',
      chooseMode: '选择方式',
      delayExample: '例如：5–7 天',
      costPerKg: '每公斤费用',
    },
    settings: {
      title: '全局设置',
      editMarquee: '编辑滚动条',
      newSetting: '新建参数',
      totalSettings: '参数总数',
      marquee: '滚动条',
      key: '键',
      value: '值',
      noSettings: '未配置参数',
      keyField: '键 (kkey)',
      valueHint: '输入值（支持表情：🎉 ✨ 🚀）',
      purpose: '此参数的用途？',
    },
    activityLogs: {
      title: '活动日志',
      action: '操作',
      creation: '创建',
      modification: '修改',
      deletion: '删除',
      entityType: '实体类型',
      since: '从',
      until: '至',
      when: '时间',
      who: '操作人',
      target: '目标',
      ip: 'IP',
      browser: '浏览器',
      details: '详情',
      noActivity: '暂无活动记录…',
      activityDetail: '活动详情',
      entity: '实体',
      associatedData: '关联数据',
    },
    contactLeads: {
      title: '联系请求（网站）',
      searchHint: '姓名、邮箱、主题、留言…',
      email: '邮箱',
      phone: '电话',
      noLeads: '暂无请求',
      leadDetail: '联系请求',
      receivedOn: '收到于',
      ipAddress: 'IP 地址',
      message: '留言',
    },
    personalShoppingHub: {
      title: '代购服务',
      subtitle: '快速访问商店目录和客户请求。',
      requests: '请求',
      trackPs: '代购请求跟踪',
      categories: '分类',
      catalogLines: '目录行类型',
      products: '产品',
      productSheets: '商店产品页',
      storefront: '店面页面',
      clientPreview: '客户端预览',
    },
    homeServices: {
      title: '服务（首页）',
      newCard: '新建卡片',
      noServices: '暂无服务 — 导入数据或创建卡片。',
      editCard: '编辑卡片',
      iconBootstrap: 'Bootstrap 图标',
      keyPoints: '要点…',
      line: '行',
    },
    guideServices: {
      title: '陪同服务（导游页面）',
      noServices: '暂无服务 — 导入数据或创建卡片。',
    },
    sitePages: {
      title: '关于 & 联系页面',
      contact: '联系',
      about: '关于',
      heroBanner: '横幅',
      threeCards: '三张卡片',
      formMap: '表单 & 地图',
      backgroundImage: '背景图',
      remove: '移除',
      iconClass: '图标类 (Font Awesome)',
      textFr: '文本 FR',
      textEn: '文本 EN',
      mapEmbedUrl: 'Google 地图 iframe URL',
      saveContact: '保存联系页面',
      missionIntro: '使命简介',
      missionBlock: '使命区块',
      badgeFr: '徽章 FR',
      badgeEn: '徽章 EN',
      buttonFr: '按钮 FR',
      buttonEn: '按钮 EN',
      buttonLink: '按钮链接',
      counters: '计数器',
      value: '数值',
      suffix: '后缀',
      labelFr: '标签 FR',
      labelEn: '标签 EN',
      saveAbout: '保存关于页面',
    },
    footerAdmin: {
      title: '页脚（公开网站）',
      textUnderLogo: 'Logo 下方文字',
      socialNetworks: '社交网络',
      contactBlocks: '联系区块',
      saveText: '保存文字',
      add: '添加',
      url: 'URL',
      noSocialLinks: '未配置链接。',
      noContactBlocks: '未配置联系区块。',
      newSocialLink: '新建社交链接',
      oneOrMoreLines: '一行或多行',
    },
  },
}

const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf8'))
const result = deepMerge(JSON.parse(JSON.stringify(en)), zh)
fs.writeFileSync(path.join(localesDir, 'zh.json'), JSON.stringify(result, null, 2) + '\n', 'utf8')
console.log('zh.json regenerated with full Chinese translations')
